## Scraping 1588 rows of data from yatra website for predicting flight price

In [1]:
# installing selenium library
!pip install selenium

Requirement already satisfied: selenium in c:\users\nitish\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\nitish\anaconda3\lib\site-packages (from selenium) (1.25.11)

In [2]:
# importing libraries
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [3]:
# connecting to webdriver
driver = webdriver.Chrome(r"C:\Users\Nitish\Downloads\Compressed\chromedriver.exe")
time.sleep(2)

In [4]:
# send get request to the webpage server to get the source code of the page
url = 'https://yatra.com/'
driver.get(url) 
time.sleep(4)

In [5]:
# Maximize current window
driver.maximize_window()

In [6]:
# clicking on search button option
driver.find_element_by_id("BE_flight_flsearch_btn").click()

In [7]:
airline1=[]
source1=[]
des1=[]
dur1=[]
dep1=[]
arvl1=[]
totstops1=[]
price1=[]

In [8]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline1.append(i.text)
except NoSuchElementException:
    airline1.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source1.append(i.text)
except NoSuchElementException:
    source1.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des1.append(i.text)
except NoSuchElementException:
    des1.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur1.append(i.text)
except NoSuchElementException:
    dur1.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep1.append(i.text)
except NoSuchElementException:
    dep1.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl1.append(i.text)
except NoSuchElementException:
    arvl1.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops1.append(i.text)
except NoSuchElementException:
    totstops1.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price1.append(i.text)
except NoSuchElementException:
    price1.append("No detail")

In [9]:
len(price1)

152

In [10]:
doj1=['29/10/2021']
doj1=doj1*152

In [12]:
flight1=pd.DataFrame({})            # making dataframe
flight1['Airline']= airline1
flight1['Date_of_Journey']=doj1
flight1['Source']= source1
flight1['Destination']= des1
flight1['Duration']= dur1
flight1['Departure Time']= dep1
flight1['Arrival Time']= arvl1
flight1['Total Stops']=totstops1
flight1['Price']= price1
flight1

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,29/10/2021,New Delhi,Mumbai,6h 35m,09:25,16:00,1 Stop,"5,953"
1,Air Asia,29/10/2021,New Delhi,Mumbai,7h 35m,12:40,20:15,1 Stop,"5,953"
2,Air Asia,29/10/2021,New Delhi,Mumbai,8h 20m,11:55,20:15,1 Stop,"5,953"
3,Air Asia,29/10/2021,New Delhi,Mumbai,14h 55m,05:20,20:15,1 Stop,"5,953"
4,Go First,29/10/2021,New Delhi,Mumbai,1h 55m,18:50,20:45,Non Stop,"5,954"
...,...,...,...,...,...,...,...,...,...
147,Air India,29/10/2021,New Delhi,Mumbai,14h 35m,16:35,07:10\n+ 1 day,1 Stop,"1 left at19,605"
148,Air India,29/10/2021,New Delhi,Mumbai,17h 05m,16:35,09:40\n+ 1 day,1 Stop,"1 left at19,605"
149,Air India,29/10/2021,New Delhi,Mumbai,5h 25m,10:15,15:40,1 Stop,"19,815"
150,Vistara,29/10/2021,New Delhi,Mumbai,5h 30m,17:35,23:05,1 Stop,"19,815"
151,Vistara,29/10/2021,New Delhi,Mumbai,7h 05m,16:00,23:05,1 Stop,"19,815"

In [13]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [14]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Kolkata")

In [15]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [16]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Bangalore")

In [17]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [18]:
# clicking on 30th october option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[3]/div').click()

In [19]:
airline2=[]
source2=[]
des2=[]
dur2=[]
dep2=[]
arvl2=[]
totstops2=[]
price2=[]

In [20]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline2.append(i.text)
except NoSuchElementException:
    airline2.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source2.append(i.text)
except NoSuchElementException:
    source2.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des2.append(i.text)
except NoSuchElementException:
    des2.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur2.append(i.text)
except NoSuchElementException:
    dur2.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep2.append(i.text)
except NoSuchElementException:
    dep2.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl2.append(i.text)
except NoSuchElementException:
    arvl2.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops2.append(i.text)
except NoSuchElementException:
    totstops2.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price2.append(i.text)
except NoSuchElementException:
    price2.append("No detail")

In [21]:
len(price2)

108

In [22]:
doj2=['30/10/2021']
doj2=doj2*108

In [23]:
flight2=pd.DataFrame({})            # making dataframe
flight2['Airline']= airline2
flight2['Date_of_Journey']=doj2
flight2['Source']= source2
flight2['Destination']= des2
flight2['Duration']= dur2
flight2['Departure Time']= dep2
flight2['Arrival Time']= arvl2
flight2['Total Stops']=totstops2
flight2['Price']= price2
flight2

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,30/10/2021,Kolkata,Bangalore,4h 35m,06:35,11:10,1 Stop,"6,486"
1,Air Asia,30/10/2021,Kolkata,Bangalore,7h 05m,08:35,15:40,1 Stop,"6,486"
2,Air Asia,30/10/2021,Kolkata,Bangalore,7h 25m,11:30,18:55,1 Stop,"6,486"
3,Air Asia,30/10/2021,Kolkata,Bangalore,8h 00m,08:35,16:35,1 Stop,"6,486"
4,Air Asia,30/10/2021,Kolkata,Bangalore,8h 30m,05:25,13:55,1 Stop,"6,486"
...,...,...,...,...,...,...,...,...,...
103,Vistara,30/10/2021,Kolkata,Bangalore,8h 15m,10:15,18:30,2 Stop(s),"22,292"
104,Air India,30/10/2021,Kolkata,Bangalore,9h 20m,06:55,16:15,1 Stop,"2 left at22,554"
105,Air Asia,30/10/2021,Kolkata,Bangalore,9h 15m,06:35,15:50,2 Stop(s),"24,155"
106,Air India,30/10/2021,Kolkata,Bangalore,28h 10m,10:35,14:45\n+ 1 day,3 Stop(s),"1 left at24,549"
107,Air India,30/10/2021,Kolkata,Bangalore,13h 20m,10:35,23:55,1 Stop,"1 left at25,809"

In [24]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [25]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Chennai")

In [26]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [27]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Lucknow")

In [28]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [29]:
# clicking on 31st october option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[4]/div').click()

In [30]:
airline3=[]
source3=[]
des3=[]
dur3=[]
dep3=[]
arvl3=[]
totstops3=[]
price3=[]

In [31]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline3.append(i.text)
except NoSuchElementException:
    airline3.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source3.append(i.text)
except NoSuchElementException:
    source3.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des3.append(i.text)
except NoSuchElementException:
    des3.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur3.append(i.text)
except NoSuchElementException:
    dur3.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep3.append(i.text)
except NoSuchElementException:
    dep3.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl3.append(i.text)
except NoSuchElementException:
    arvl3.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops3.append(i.text)
except NoSuchElementException:
    totstops3.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price3.append(i.text)
except NoSuchElementException:
    price3.append("No detail")

In [32]:
len(price3)

71

In [33]:
doj3=['31/10/2021']
doj3=doj3*71

In [34]:
flight3=pd.DataFrame({})            # making dataframe
flight3['Airline']= airline3
flight3['Date_of_Journey']=doj3
flight3['Source']= source3
flight3['Destination']= des3
flight3['Duration']= dur3
flight3['Departure Time']= dep3
flight3['Arrival Time']= arvl3
flight3['Total Stops']=totstops3
flight3['Price']= price3
flight3

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,IndiGo,31/10/2021,Chennai,Lucknow,7h 45m,22:25,06:10\n+ 1 day,1 Stop,"7,352"
1,IndiGo,31/10/2021,Chennai,Lucknow,8h 55m,22:25,07:20\n+ 1 day,1 Stop,"7,352"
2,IndiGo,31/10/2021,Chennai,Lucknow,9h 20m,08:25,17:45,1 Stop,"7,352"
3,IndiGo,31/10/2021,Chennai,Lucknow,9h 40m,22:15,07:55\n+ 1 day,1 Stop,"7,352"
4,IndiGo,31/10/2021,Chennai,Lucknow,10h 25m,22:25,08:50\n+ 1 day,1 Stop,"7,352"
...,...,...,...,...,...,...,...,...,...
66,Air India,31/10/2021,Chennai,Lucknow,13h 30m,06:10,19:40,1 Stop,"29,193"
67,Air India,31/10/2021,Chennai,Lucknow,15h 15m,17:00,08:15\n+ 1 day,1 Stop,"1 left at29,508"
68,Air India,31/10/2021,Chennai,Lucknow,13h 20m,06:20,19:40,2 Stop(s),"30,138"
69,Air India,31/10/2021,Chennai,Lucknow,22h 20m,09:55,08:15\n+ 1 day,1 Stop,"1 left at31,818"
70,Air India,31/10/2021,Chennai,Lucknow,26h 05m,06:10,08:15\n+ 1 day,1 Stop,"31,818"

In [35]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [36]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Bangalore")

In [37]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [38]:
search=driver.find_element_by_id('destination_0')
search.send_keys("New Delhi")

In [39]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [40]:
# clicking on 2nd November option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[6]/div').click()

In [41]:
airline4=[]
source4=[]
des4=[]
dur4=[]
dep4=[]
arvl4=[]
totstops4=[]
price4=[]

In [42]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline4.append(i.text)
except NoSuchElementException:
    airline4.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source4.append(i.text)
except NoSuchElementException:
    source4.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des4.append(i.text)
except NoSuchElementException:
    des4.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur4.append(i.text)
except NoSuchElementException:
    dur4.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep4.append(i.text)
except NoSuchElementException:
    dep4.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl4.append(i.text)
except NoSuchElementException:
    arvl4.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops4.append(i.text)
except NoSuchElementException:
    totstops4.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price4.append(i.text)
except NoSuchElementException:
    price4.append("No detail")

In [43]:
len(price4)

156

In [44]:
doj4=['02/11/2021']
doj4=doj4*156

In [45]:
flight4=pd.DataFrame({})            # making dataframe
flight4['Airline']= airline4
flight4['Date_of_Journey']=doj4
flight4['Source']= source4
flight4['Destination']= des4
flight4['Duration']= dur4
flight4['Departure Time']= dep4
flight4['Arrival Time']= arvl4
flight4['Total Stops']=totstops4
flight4['Price']= price4
flight4

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,02/11/2021,Bangalore,New Delhi,5h 30m,05:25,10:55,1 Stop,"7,486"
1,Air Asia,02/11/2021,Bangalore,New Delhi,6h 20m,05:40,12:00,1 Stop,"7,486"
2,Air Asia,02/11/2021,Bangalore,New Delhi,7h 10m,09:05,16:15,1 Stop,"7,486"
3,Air Asia,02/11/2021,Bangalore,New Delhi,7h 35m,11:45,19:20,1 Stop,"7,486"
4,Air Asia,02/11/2021,Bangalore,New Delhi,7h 50m,13:00,20:50,1 Stop,"7,486"
...,...,...,...,...,...,...,...,...,...
151,Air Asia,02/11/2021,Bangalore,New Delhi,7h 40m,18:30,02:10\n+ 1 day,1 Stop,"15,469"
152,Air India,02/11/2021,Bangalore,New Delhi,14h 50m,06:40,21:30,2 Stop(s),"3 left at16,152"
153,Air Asia,02/11/2021,Bangalore,New Delhi,8h 45m,07:30,16:15,2 Stop(s),"16,726"
154,Air India,02/11/2021,Bangalore,New Delhi,6h 05m,15:30,21:35,1 Stop,"17,569"
155,Vistara,02/11/2021,Bangalore,New Delhi,4h 45m,12:20,17:05,1 Stop,"20,719"

In [46]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [47]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Ranchi")

In [48]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [49]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Chennai")

In [50]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [51]:
# clicking on 5th November option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[9]/div').click()

In [52]:
airline5=[]
source5=[]
des5=[]
dur5=[]
dep5=[]
arvl5=[]
totstops5=[]
price5=[]

In [53]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline5.append(i.text)
except NoSuchElementException:
    airline5.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source5.append(i.text)
except NoSuchElementException:
    source5.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des5.append(i.text)
except NoSuchElementException:
    des5.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur5.append(i.text)
except NoSuchElementException:
    dur5.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep5.append(i.text)
except NoSuchElementException:
    dep5.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl5.append(i.text)
except NoSuchElementException:
    arvl5.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops5.append(i.text)
except NoSuchElementException:
    totstops5.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price5.append(i.text)
except NoSuchElementException:
    price5.append("No detail")

In [54]:
len(price5)

55

In [55]:
doj5=['05/11/2021']
doj5=doj5*55

In [56]:
flight5=pd.DataFrame({})            # making dataframe
flight5['Airline']= airline5
flight5['Date_of_Journey']=doj5
flight5['Source']= source5
flight5['Destination']= des5
flight5['Duration']= dur5
flight5['Departure Time']= dep5
flight5['Arrival Time']= arvl5
flight5['Total Stops']=totstops5
flight5['Price']= price5
flight5

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,05/11/2021,Ranchi,Chennai,4h 15m,12:15,16:30,1 Stop,"4,267"
1,Air Asia,05/11/2021,Ranchi,Chennai,6h 40m,09:50,16:30,1 Stop,"4,267"
2,IndiGo,05/11/2021,Ranchi,Chennai,2h 20m,14:35,16:55,Non Stop,"4,269"
3,Air Asia,05/11/2021,Ranchi,Chennai,2h 40m,12:25,15:05,Non Stop,"4,270"
4,IndiGo,05/11/2021,Ranchi,Chennai,7h 35m,14:00,21:35,1 Stop,"5,319"
5,IndiGo,05/11/2021,Ranchi,Chennai,8h 00m,09:40,17:40,1 Stop,"5,319"
6,IndiGo,05/11/2021,Ranchi,Chennai,9h 10m,09:40,18:50,1 Stop,"5,319"
7,IndiGo,05/11/2021,Ranchi,Chennai,9h 15m,14:00,23:15,1 Stop,"5,319"
8,IndiGo,05/11/2021,Ranchi,Chennai,9h 20m,20:35,05:55\n+ 1 day,1 Stop,"5,319"
9,IndiGo,05/11/2021,Ranchi,Chennai,10h 25m,09:40,20:05,1 Stop,"5,319"
10,IndiGo,05/11/2021,Ranchi,Chennai,11h 00m,14:00,01:00\n+ 1 day,1 Stop,"5,319"
11,IndiGo,05/11/2021,Ranchi,Chennai,5h 25m,09:40,15:05,1 Stop,"5,897"
12,IndiGo,05/11/2021,Ranchi,Chennai,8h 05m,18:10,02:15\n+ 1 day,1 Stop,"5,897"
13,Go First,05/11/2021,Ranchi,Chennai,12h 25m,19:15,07:40\n+ 1 day,1 Stop,"3 left at5,947"
14,IndiGo,05/11/2021,Ranchi,Chennai,5h 55m,18:10,00:05\n+ 1 day,1 Stop,"6,474"
15,IndiGo,05/11/2021,Ranchi,Chennai,5h 55m,20:20,02:15\n+ 1 day,1 Stop,"6,474"
16,IndiGo,05/11/2021,Ranchi,Chennai,11h 20m,08:50,20:10,1 Stop,"1 left at6,474"
17,IndiGo,05/11/2021,Ranchi,Chennai,7h 15m,18:40,01:55\n+ 1 day,1 Stop,"7,052"
18,IndiGo,05/11/2021,Ranchi,Chennai,7h 55m,07:45,15:40,1 Stop,"7,052"
19,IndiGo,05/11/2021,Ranchi,Chennai,12h 35m,13:20,01:55\n+ 1 day,1 Stop,"7,052"
20,IndiGo,05/11/2021,Ranchi,Chennai,8h 25m,13:20,21:45,1 Stop,"7,629"
21,IndiGo,05/11/2021,Ranchi,Chennai,10h 00m,13:20,23:20,1 Stop,"7,629"
22,IndiGo,05/11/2021,Ranchi,Chennai,11h 25m,07:45,19:10,1 Stop,"7,629"
23,IndiGo,05/11/2021,Ranchi,Chennai,8h 30m,08:50,17:20,1 Stop,"3 left at8,207"
24,IndiGo,05/11/2021,Ranchi,Chennai,7h 05m,13:20,20:25,1 Stop,"8,784"
25,IndiGo,05/11/2021,Ranchi,Chennai,12h 40m,07:45,20:25,1 Stop,"8,784"
26,Vistara,05/11/2021,Ranchi,Chennai,7h 25m,08:55,16:20,1 Stop,"11,135"
27,Vistara,05/11/2021,Ranchi,Chennai,13h 45m,20:15,10:00\n+ 1 day,1 Stop,"11,135"
28,Vistara,05/11/2021,Ranchi,Chennai,13h 50m,08:55,22:45,1 Stop,"11,135"
29,Vistara,05/11/2021,Ranchi,Chennai,20h 05m,20:15,16:20\n+ 1 day,1 Stop,"11,135"
30,Vistara,05/11/2021,Ranchi,Chennai,25h 05m,08:55,10:00\n+ 1 day,1 Stop,"11,135"
31,Air India,05/11/2021,Ranchi,Chennai,18h 30m,13:30,08:00\n+ 1 day,2 Stop(s),"11,475"
32,Vistara,05/11/2021,Ranchi,Chennai,11h 20m,08:55,20:15,1 Stop,"11,849"
33,Vistara,05/11/2021,Ranchi,Chennai,24h 00m,20:15,20:15\n+ 1 day,1 Stop,"11,849"
34,Air India,05/11/2021,Ranchi,Chennai,23h 20m,13:30,12:50\n+ 1 day,2 Stop(s),"12,252"
35,Air India,05/11/2021,Ranchi,Chennai,23h 20m,13:30,12:50\n+ 1 day,2 Stop(s),"12,252"
36,Air India,05/11/2021,Ranchi,Chennai,23h 20m,13:30,12:50\n+ 1 day,2 Stop(s),"12,252"
37,Vistara,05/11/2021,Ranchi,Chennai,26h 30m,20:15,22:45\n+ 1 day,1 Stop,"12,474"
38,Air India,05/11/2021,Ranchi,Chennai,6h 15m,13:25,19:40,1 Stop,"13,509"
39,Air India,05/11/2021,Ranchi,Chennai,10h 05m,13:30,23:35,1 Stop,"14,244"
40,Air India,05/11/2021,Ranchi,Chennai,14h 10m,09:25,23:35,2 Stop(s),"1 left at14,720"
41,Vistara,05/11/2021,Ranchi,Chennai,11h 00m,08:55,19:55,2 Stop(s),"15,450"
42,Vistara,05/11/2021,Ranchi,Chennai,11h 00m,08:55,19:55,2 Stop(s),"15,450"
43,Vistara,05/11/2021,Ranchi,Chennai,14h 10m,08:55,23:05,2 Stop(s),"15,450"
44,Vistara,05/11/2021,Ranchi,Chennai,14h 10m,08:55,23:05,2 Stop(s),"15,450"
45,Air India,05/11/2021,Ranchi,Chennai,21h 55m,09:25,07:20\n+ 1 day,2 Stop(s),"1 left at16,106"
46,Air India,05/11/2021,Ranchi,Chennai,17h 50m,13:30,07:20\n+ 1 day,2 Stop(s),"16,725"
47,Air India,05/11/2021,Ranchi,Chennai,17h 50m,13:30,07:20\n+ 1 day,2 Stop(s),"16,725"
48,Air India,05/11/2021,Ranchi,Chennai,17h 50m,13:30,07:20\n+ 1 day,2 Stop(s),"16,725"
49,Air India,05/11/2021,Ranchi,Chennai,17h 50m,13:30,07:20\n+ 1 day,3 Stop(s),"16,725"
50,Air India,05/11/2021,Ranchi,Chennai,38h 10m,09:25,23:35\n+ 1 day,2 Stop(s),"1 left at17,145"
51,Air India,05/11/2021,Ranchi,Chennai,19h 25m,13:30,08:55\n+ 1 day,1 Stop,"17,499"
52,Air India,05/11/2021,Ranchi,Chennai,23h 30m,09:25,08:55\n+ 1 day,2 Stop(s),"1 left at18,300"
53,Air India,05/11/2021,Ranchi,Chennai,23h 30m,09:25,08:55\n+ 1 day,2 Stop(s),"1 left at18,300"
54,Air India,05/11/2021,Ranchi,Chennai,23h 10m,13:30,12:40\n+ 1 day,1 Stop,"20,859"

In [57]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [58]:
search=driver.find_element_by_id('origin_0')
search.send_keys("New Delhi")

In [59]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [60]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Cochin")

In [61]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [62]:
# clicking on 8th November option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[12]/div').click()

In [63]:
airline6=[]
source6=[]
des6=[]
dur6=[]
dep6=[]
arvl6=[]
totstops6=[]
price6=[]

In [64]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline6.append(i.text)
except NoSuchElementException:
    airline6.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source6.append(i.text)
except NoSuchElementException:
    source6.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des6.append(i.text)
except NoSuchElementException:
    des6.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur6.append(i.text)
except NoSuchElementException:
    dur6.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep6.append(i.text)
except NoSuchElementException:
    dep6.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl6.append(i.text)
except NoSuchElementException:
    arvl6.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops6.append(i.text)
except NoSuchElementException:
    totstops6.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price6.append(i.text)
except NoSuchElementException:
    price6.append("No detail")

In [65]:
len(price6)

70

In [66]:
doj6=['08/11/2021']
doj6=doj6*70

In [67]:
flight6=pd.DataFrame({})            # making dataframe
flight6['Airline']= airline6
flight6['Date_of_Journey']=doj6
flight6['Source']= source6
flight6['Destination']= des6
flight6['Duration']= dur6
flight6['Departure Time']= dep6
flight6['Arrival Time']= arvl6
flight6['Total Stops']=totstops6
flight6['Price']= price6
flight6

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Vistara,08/11/2021,New Delhi,Kochi,3h 10m,16:00,19:10,Non Stop,"9,105"
1,IndiGo,08/11/2021,New Delhi,Kochi,3h 15m,19:30,22:45,Non Stop,"9,105"
2,IndiGo,08/11/2021,New Delhi,Kochi,5h 50m,16:20,22:10,1 Stop,"9,105"
3,IndiGo,08/11/2021,New Delhi,Kochi,5h 55m,12:45,18:40,1 Stop,"9,105"
4,IndiGo,08/11/2021,New Delhi,Kochi,5h 55m,17:45,23:40,1 Stop,"9,105"
...,...,...,...,...,...,...,...,...,...
65,IndiGo,08/11/2021,New Delhi,Kochi,8h 25m,04:45,13:10,1 Stop,"14,507"
66,IndiGo,08/11/2021,New Delhi,Kochi,9h 35m,01:05,10:40,1 Stop,"14,565"
67,Air India,08/11/2021,New Delhi,Kochi,19h 40m,13:30,09:10\n+ 1 day,2 Stop(s),"16,298"
68,IndiGo,08/11/2021,New Delhi,Kochi,10h 05m,08:35,18:40,1 Stop,"19,138"
69,Air India,08/11/2021,New Delhi,Kochi,9h 00m,10:15,19:15,2 Stop(s),"20,459"

In [68]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [69]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Pune")

In [70]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [71]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Kolkata")

In [72]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [73]:
# clicking on 11th November option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[14]/div').click()

In [74]:
airline7=[]
source7=[]
des7=[]
dur7=[]
dep7=[]
arvl7=[]
totstops7=[]
price7=[]

In [75]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline7.append(i.text)
except NoSuchElementException:
    airline7.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source7.append(i.text)
except NoSuchElementException:
    source7.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des7.append(i.text)
except NoSuchElementException:
    des7.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur7.append(i.text)
except NoSuchElementException:
    dur7.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep7.append(i.text)
except NoSuchElementException:
    dep7.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl7.append(i.text)
except NoSuchElementException:
    arvl7.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops7.append(i.text)
except NoSuchElementException:
    totstops7.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price7.append(i.text)
except NoSuchElementException:
    price7.append("No detail")

In [76]:
len(price7)

88

In [77]:
doj7=['11/11/2021']
doj7=doj7*88

In [78]:
flight7=pd.DataFrame({})            # making dataframe
flight7['Airline']= airline7
flight7['Date_of_Journey']=doj7
flight7['Source']= source7
flight7['Destination']= des7
flight7['Duration']= dur7
flight7['Departure Time']= dep7
flight7['Arrival Time']= arvl7
flight7['Total Stops']=totstops7
flight7['Price']= price7
flight7

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,11/11/2021,Pune,Kolkata,5h 20m,17:50,23:10,1 Stop,"7,741"
1,Air Asia,11/11/2021,Pune,Kolkata,6h 00m,19:25,01:25\n+ 1 day,1 Stop,"7,741"
2,Air Asia,11/11/2021,Pune,Kolkata,6h 10m,19:25,01:35\n+ 1 day,1 Stop,"7,741"
3,Air Asia,11/11/2021,Pune,Kolkata,7h 30m,11:50,19:20,1 Stop,"7,741"
4,Air Asia,11/11/2021,Pune,Kolkata,12h 30m,18:40,07:10\n+ 1 day,1 Stop,"7,741"
...,...,...,...,...,...,...,...,...,...
83,Vistara,11/11/2021,Pune,Kolkata,16h 50m,16:55,09:45\n+ 1 day,2 Stop(s),"19,293"
84,Vistara,11/11/2021,Pune,Kolkata,20h 35m,13:10,09:45\n+ 1 day,2 Stop(s),"19,608"
85,Air India,11/11/2021,Pune,Kolkata,20h 15m,12:35,08:50\n+ 1 day,3 Stop(s),"24,228"
86,Air India,11/11/2021,Pune,Kolkata,20h 15m,12:35,08:50\n+ 1 day,3 Stop(s),"24,648"
87,Air India,11/11/2021,Pune,Kolkata,20h 15m,12:35,08:50\n+ 1 day,3 Stop(s),"25,488"

In [79]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [80]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Goa")

In [81]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [82]:
search=driver.find_element_by_id('destination_0')
search.send_keys("New Delhi")

In [83]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [84]:
# clicking on 10th November option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[10]/div').click()

In [85]:
airline8=[]
source8=[]
des8=[]
dur8=[]
dep8=[]
arvl8=[]
totstops8=[]
price8=[]

In [86]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline8.append(i.text)
except NoSuchElementException:
    airline8.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source8.append(i.text)
except NoSuchElementException:
    source8.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des8.append(i.text)
except NoSuchElementException:
    des8.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur8.append(i.text)
except NoSuchElementException:
    dur8.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep8.append(i.text)
except NoSuchElementException:
    dep8.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl8.append(i.text)
except NoSuchElementException:
    arvl8.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops8.append(i.text)
except NoSuchElementException:
    totstops8.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price8.append(i.text)
except NoSuchElementException:
    price8.append("No detail")

In [87]:
len(price8)

140

In [107]:
doj8=['10/11/2021']
doj8=doj8*140

In [108]:
flight8=pd.DataFrame({})            # making dataframe
flight8['Airline']= airline8
flight8['Date_of_Journey']=doj8
flight8['Source']= source8
flight8['Destination']= des8
flight8['Duration']= dur8
flight8['Departure Time']= dep8
flight8['Arrival Time']= arvl8
flight8['Total Stops']=totstops8
flight8['Price']= price8
flight8

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,10/11/2021,Goa,New Delhi,5h 05m,22:30,03:35\n+ 1 day,1 Stop,"7,624"
1,Air Asia,10/11/2021,Goa,New Delhi,6h 30m,07:35,14:05,1 Stop,"7,624"
2,Air Asia,10/11/2021,Goa,New Delhi,6h 45m,20:05,02:50\n+ 1 day,2 Stop(s),"7,624"
3,Air Asia,10/11/2021,Goa,New Delhi,7h 30m,20:05,03:35\n+ 1 day,2 Stop(s),"7,624"
4,Air Asia,10/11/2021,Goa,New Delhi,8h 40m,07:35,16:15,2 Stop(s),"7,624"
...,...,...,...,...,...,...,...,...,...
135,Air India,10/11/2021,Goa,New Delhi,19h 30m,23:00,18:30\n+ 1 day,3 Stop(s),"17,638"
136,IndiGo,10/11/2021,Goa,New Delhi,6h 40m,14:40,21:20,1 Stop,"1 left at18,074"
137,SpiceJet,10/11/2021,Goa,New Delhi,8h 45m,21:05,05:50\n+ 1 day,1 Stop,"19,044"
138,IndiGo,10/11/2021,Goa,New Delhi,5h 25m,17:05,22:30,1 Stop,"1 left at19,071"
139,SpiceJet,10/11/2021,Goa,New Delhi,10h 40m,21:05,07:45\n+ 1 day,1 Stop,"19,148"

In [90]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [91]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Hyderabad")

In [92]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [93]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Ahmedabad")

In [94]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [95]:
# clicking on calendar option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/i').click()

In [96]:
# clicking on 27th november option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/table/tbody/tr[4]/td[7]/div').click()

In [97]:
airline9=[]
source9=[]
des9=[]
dur9=[]
dep9=[]
arvl9=[]
totstops9=[]
price9=[]

In [98]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline9.append(i.text)
except NoSuchElementException:
    airline9.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source9.append(i.text)
except NoSuchElementException:
    source9.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des9.append(i.text)
except NoSuchElementException:
    des9.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur9.append(i.text)
except NoSuchElementException:
    dur9.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep9.append(i.text)
except NoSuchElementException:
    dep9.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl9.append(i.text)
except NoSuchElementException:
    arvl9.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops9.append(i.text)
except NoSuchElementException:
    totstops9.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price9.append(i.text)
except NoSuchElementException:
    price9.append("No detail")

In [99]:
len(price9)

87

In [109]:
doj9=['27/11/2021']
doj9=doj9*87

In [110]:
flight9=pd.DataFrame({})            # making dataframe
flight9['Airline']= airline9
flight9['Date_of_Journey']=doj9
flight9['Source']= source9
flight9['Destination']= des9
flight9['Duration']= dur9
flight9['Departure Time']= dep9
flight9['Arrival Time']= arvl9
flight9['Total Stops']=totstops9
flight9['Price']= price9
flight9

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,IndiGo,27/11/2021,Hyderabad,Ahmedabad,7h 35m,17:45,01:20\n+ 1 day,1 Stop,"2,346"
1,IndiGo,27/11/2021,Hyderabad,Ahmedabad,1h 45m,05:55,07:40,Non Stop,"3,403"
2,IndiGo,27/11/2021,Hyderabad,Ahmedabad,6h 05m,17:05,23:10,1 Stop,"3,558"
3,IndiGo,27/11/2021,Hyderabad,Ahmedabad,6h 15m,13:40,19:55,1 Stop,"4 left at3,558"
4,IndiGo,27/11/2021,Hyderabad,Ahmedabad,8h 20m,13:40,22:00,1 Stop,"1 left at3,558"
...,...,...,...,...,...,...,...,...,...
82,Air India,27/11/2021,Hyderabad,Ahmedabad,23h 55m,20:45,20:40\n+ 1 day,2 Stop(s),"2 left at9,477"
83,Air India,27/11/2021,Hyderabad,Ahmedabad,23h 55m,20:45,20:40\n+ 1 day,2 Stop(s),"2 left at9,477"
84,Air India,27/11/2021,Hyderabad,Ahmedabad,11h 40m,06:30,18:10,2 Stop(s),"9,493"
85,Air India,27/11/2021,Hyderabad,Ahmedabad,12h 10m,06:00,18:10,2 Stop(s),"9,516"
86,Air India,27/11/2021,Hyderabad,Ahmedabad,28h 35m,13:15,17:50\n+ 1 day,3 Stop(s),"2 left at9,588"

In [102]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [103]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Bhubaneswar")

In [104]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [105]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Bangalore")

In [106]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [111]:
# clicking on 29th november option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[13]/div').click()

In [112]:
airline10=[]
source10=[]
des10=[]
dur10=[]
dep10=[]
arvl10=[]
totstops10=[]
price10=[]

In [113]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline10.append(i.text)
except NoSuchElementException:
    airline10.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source10.append(i.text)
except NoSuchElementException:
    source10.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des10.append(i.text)
except NoSuchElementException:
    des10.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur10.append(i.text)
except NoSuchElementException:
    dur10.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep10.append(i.text)
except NoSuchElementException:
    dep10.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl10.append(i.text)
except NoSuchElementException:
    arvl10.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops10.append(i.text)
except NoSuchElementException:
    totstops10.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price10.append(i.text)
except NoSuchElementException:
    price10.append("No detail")

In [114]:
len(price10)

85

In [115]:
doj10=['29/11/2021']
doj10=doj10*85

In [116]:
flight10=pd.DataFrame({})            # making dataframe
flight10['Airline']= airline10
flight10['Date_of_Journey']=doj10
flight10['Source']= source10
flight10['Destination']= des10
flight10['Duration']= dur10
flight10['Departure Time']= dep10
flight10['Arrival Time']= arvl10
flight10['Total Stops']=totstops10
flight10['Price']= price10
flight10

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,29/11/2021,Bhubaneswar,Bangalore,1h 50m,21:55,23:45,Non Stop,"2,977"
1,IndiGo,29/11/2021,Bhubaneswar,Bangalore,2h 15m,23:10,01:25\n+ 1 day,Non Stop,"2,977"
2,Air Asia,29/11/2021,Bhubaneswar,Bangalore,2h 10m,09:05,11:15,Non Stop,"3,653"
3,IndiGo,29/11/2021,Bhubaneswar,Bangalore,2h 10m,08:00,10:10,Non Stop,"3,950"
4,IndiGo,29/11/2021,Bhubaneswar,Bangalore,9h 40m,21:15,06:55\n+ 1 day,1 Stop,"4,304"
...,...,...,...,...,...,...,...,...,...
80,IndiGo,29/11/2021,Bhubaneswar,Bangalore,5h 40m,13:15,18:55,1 Stop,"18,084"
81,IndiGo,29/11/2021,Bhubaneswar,Bangalore,7h 55m,13:15,21:10,1 Stop,"18,084"
82,IndiGo,29/11/2021,Bhubaneswar,Bangalore,9h 25m,13:15,22:40,1 Stop,"18,084"
83,IndiGo,29/11/2021,Bhubaneswar,Bangalore,10h 50m,13:15,00:05\n+ 1 day,1 Stop,"18,084"
84,Vistara,29/11/2021,Bhubaneswar,Bangalore,19h 30m,20:30,16:00\n+ 1 day,2 Stop(s),"18,132"

In [117]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [118]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Chandigarh")

In [119]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [120]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Mumbai")

In [121]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [122]:
# clicking on calendar option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]').click()

In [123]:
# clicking on next option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/span').click()

In [124]:
# clicking on 13th december option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/table/tbody/tr[3]/td[2]/div').click()

In [125]:
airline11=[]
source11=[]
des11=[]
dur11=[]
dep11=[]
arvl11=[]
totstops11=[]
price11=[]

In [126]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline11.append(i.text)
except NoSuchElementException:
    airline11.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source11.append(i.text)
except NoSuchElementException:
    source11.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des11.append(i.text)
except NoSuchElementException:
    des11.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur11.append(i.text)
except NoSuchElementException:
    dur11.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep11.append(i.text)
except NoSuchElementException:
    dep11.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl11.append(i.text)
except NoSuchElementException:
    arvl11.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops11.append(i.text)
except NoSuchElementException:
    totstops11.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price11.append(i.text)
except NoSuchElementException:
    price11.append("No detail")

In [127]:
len(price11)

109

In [128]:
doj11=['13/12/2021']
doj11=doj11*109

In [129]:
flight11=pd.DataFrame({})            # making dataframe
flight11['Airline']= airline11
flight11['Date_of_Journey']=doj11
flight11['Source']= source11
flight11['Destination']= des11
flight11['Duration']= dur11
flight11['Departure Time']= dep11
flight11['Arrival Time']= arvl11
flight11['Total Stops']=totstops11
flight11['Price']= price11
flight11

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,IndiGo,13/12/2021,Chandigarh,Mumbai,2h 25m,06:15,08:40,Non Stop,"3,398"
1,IndiGo,13/12/2021,Chandigarh,Mumbai,2h 30m,12:25,14:55,Non Stop,"3,789"
2,Vistara,13/12/2021,Chandigarh,Mumbai,4h 00m,18:50,22:50,1 Stop,"3,867"
3,Vistara,13/12/2021,Chandigarh,Mumbai,5h 00m,18:50,23:50,1 Stop,"3,867"
4,Vistara,13/12/2021,Chandigarh,Mumbai,13h 10m,18:50,08:00\n+ 1 day,1 Stop,"3,867"
...,...,...,...,...,...,...,...,...,...
104,IndiGo,13/12/2021,Chandigarh,Mumbai,12h 40m,10:30,23:10,2 Stop(s),"10,985"
105,Air India,13/12/2021,Chandigarh,Mumbai,11h 10m,11:00,22:10,2 Stop(s),"2 left at11,608"
106,Vistara,13/12/2021,Chandigarh,Mumbai,8h 05m,15:25,23:30,2 Stop(s),"14,352"
107,Vistara,13/12/2021,Chandigarh,Mumbai,21h 35m,15:25,13:00\n+ 1 day,2 Stop(s),"14,352"
108,Vistara,13/12/2021,Chandigarh,Mumbai,28h 55m,15:25,20:20\n+ 1 day,2 Stop(s),"14,352"

In [130]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [131]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Jaipur")

In [132]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [133]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Bangalore")

In [134]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [135]:
# clicking on 10th december option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[1]/div/ul/li[8]/div').click()

In [136]:
airline12=[]
source12=[]
des12=[]
dur12=[]
dep12=[]
arvl12=[]
totstops12=[]
price12=[]

In [137]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline12.append(i.text)
except NoSuchElementException:
    airline12.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source12.append(i.text)
except NoSuchElementException:
    source12.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des12.append(i.text)
except NoSuchElementException:
    des12.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur12.append(i.text)
except NoSuchElementException:
    dur12.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep12.append(i.text)
except NoSuchElementException:
    dep12.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl12.append(i.text)
except NoSuchElementException:
    arvl12.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops12.append(i.text)
except NoSuchElementException:
    totstops12.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price12.append(i.text)
except NoSuchElementException:
    price12.append("No detail")

In [138]:
len(price12)

86

In [139]:
doj12=['10/12/2021']
doj12=doj12*86

In [140]:
flight12=pd.DataFrame({})            # making dataframe
flight12['Airline']= airline12
flight12['Date_of_Journey']=doj12
flight12['Source']= source12
flight12['Destination']= des12
flight12['Duration']= dur12
flight12['Departure Time']= dep12
flight12['Arrival Time']= arvl12
flight12['Total Stops']=totstops12
flight12['Price']= price12
flight12

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,10/12/2021,Jaipur,Bangalore,3h 25m,17:15,20:40,1 Stop,"3,540"
1,Air Asia,10/12/2021,Jaipur,Bangalore,3h 40m,11:50,15:30,1 Stop,"3,540"
2,Air Asia,10/12/2021,Jaipur,Bangalore,4h 20m,10:25,14:45,1 Stop,"3,540"
3,Air Asia,10/12/2021,Jaipur,Bangalore,4h 35m,20:10,00:45\n+ 1 day,1 Stop,"3,540"
4,IndiGo,10/12/2021,Jaipur,Bangalore,4h 45m,04:50,09:35,1 Stop,"4,047"
...,...,...,...,...,...,...,...,...,...
81,Air India,10/12/2021,Jaipur,Bangalore,9h 30m,07:35,17:05,2 Stop(s),"11,136"
82,Air India,10/12/2021,Jaipur,Bangalore,22h 30m,14:00,12:30\n+ 1 day,2 Stop(s),"11,308"
83,Air India,10/12/2021,Jaipur,Bangalore,26h 15m,14:00,16:15\n+ 1 day,2 Stop(s),"11,308"
84,Air India,10/12/2021,Jaipur,Bangalore,26h 15m,14:00,16:15\n+ 1 day,2 Stop(s),"11,308"
85,Air India,10/12/2021,Jaipur,Bangalore,26h 15m,14:00,16:15\n+ 1 day,2 Stop(s),"11,308"

In [154]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [155]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Mumbai")

In [156]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [157]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Bangalore")

In [158]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [159]:
airline13=[]
source13=[]
des13=[]
dur13=[]
dep13=[]
arvl13=[]
totstops13=[]
price13=[]

In [160]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline13.append(i.text)
except NoSuchElementException:
    airline13.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source13.append(i.text)
except NoSuchElementException:
    source13.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des13.append(i.text)
except NoSuchElementException:
    des13.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur13.append(i.text)
except NoSuchElementException:
    dur13.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep13.append(i.text)
except NoSuchElementException:
    dep13.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl13.append(i.text)
except NoSuchElementException:
    arvl13.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops13.append(i.text)
except NoSuchElementException:
    totstops13.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price13.append(i.text)
except NoSuchElementException:
    price13.append("No detail")

In [161]:
len(price13)

134

In [162]:
doj13=['29/10/2021']
doj13=doj13*134

In [163]:
flight13=pd.DataFrame({})            # making dataframe
flight13['Airline']= airline13
flight13['Date_of_Journey']=doj13
flight13['Source']= source13
flight13['Destination']= des13
flight13['Duration']= dur13
flight13['Departure Time']= dep13
flight13['Arrival Time']= arvl13
flight13['Total Stops']=totstops13
flight13['Price']= price13
flight13

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air Asia,29/10/2021,Mumbai,Bangalore,7h 30m,14:55,22:25,1 Stop,"5,100"
1,Go First,29/10/2021,Mumbai,Bangalore,8h 30m,13:50,22:20,1 Stop,"5,100"
2,Air Asia,29/10/2021,Mumbai,Bangalore,10h 40m,05:55,16:35,2 Stop(s),"5,100"
3,Go First,29/10/2021,Mumbai,Bangalore,12h 20m,10:00,22:20,1 Stop,"5,100"
4,Air Asia,29/10/2021,Mumbai,Bangalore,12h 25m,05:55,18:20,1 Stop,"5,100"
...,...,...,...,...,...,...,...,...,...
129,Air India,29/10/2021,Mumbai,Bangalore,14h 55m,18:00,08:55\n+ 1 day,1 Stop,"1 left at23,163"
130,Air India,29/10/2021,Mumbai,Bangalore,9h 40m,07:55,17:35,2 Stop(s),"3 left at25,893"
131,Air India,29/10/2021,Mumbai,Bangalore,26h 25m,20:55,23:20\n+ 1 day,1 Stop,"1 left at26,733"
132,Air India,29/10/2021,Mumbai,Bangalore,15h 45m,07:55,23:40,1 Stop,"3 left at27,604"
133,Air India,29/10/2021,Mumbai,Bangalore,18h 30m,18:00,12:30\n+ 1 day,1 Stop,"1 left at30,198"

In [164]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [165]:
search=driver.find_element_by_id('origin_0')
search.send_keys("Lucknow")

In [166]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [167]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Mumbai")

In [168]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [169]:
airline14=[]
source14=[]
des14=[]
dur14=[]
dep14=[]
arvl14=[]
totstops14=[]
price14=[]

In [170]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline14.append(i.text)
except NoSuchElementException:
    airline14.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source14.append(i.text)
except NoSuchElementException:
    source14.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des14.append(i.text)
except NoSuchElementException:
    des14.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur14.append(i.text)
except NoSuchElementException:
    dur14.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep14.append(i.text)
except NoSuchElementException:
    dep14.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl14.append(i.text)
except NoSuchElementException:
    arvl14.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops14.append(i.text)
except NoSuchElementException:
    totstops14.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price14.append(i.text)
except NoSuchElementException:
    price14.append("No detail")

In [171]:
len(price14)

106

In [172]:
doj14=['29/10/2021']
doj14=doj14*106

In [173]:
flight14=pd.DataFrame({})            # making dataframe
flight14['Airline']= airline14
flight14['Date_of_Journey']=doj14
flight14['Source']= source14
flight14['Destination']= des14
flight14['Duration']= dur14
flight14['Departure Time']= dep14
flight14['Arrival Time']= arvl14
flight14['Total Stops']=totstops14
flight14['Price']= price14
flight14

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Go First,29/10/2021,Lucknow,Mumbai,2h 10m,06:35,08:45,Non Stop,"7,462"
1,Go First,29/10/2021,Lucknow,Mumbai,2h 10m,13:35,15:45,Non Stop,"7,462"
2,Go First,29/10/2021,Lucknow,Mumbai,2h 15m,20:10,22:25,Non Stop,"7,462"
3,Go First,29/10/2021,Lucknow,Mumbai,4h 20m,19:15,23:35,1 Stop,"7,462"
4,Go First,29/10/2021,Lucknow,Mumbai,4h 45m,06:20,11:05,1 Stop,"7,462"
...,...,...,...,...,...,...,...,...,...
101,Air India,29/10/2021,Lucknow,Mumbai,12h 20m,08:55,21:15,1 Stop,"19,644"
102,Air India,29/10/2021,Lucknow,Mumbai,13h 15m,08:55,22:10,1 Stop,"19,644"
103,Air India,29/10/2021,Lucknow,Mumbai,17h 15m,17:20,10:35\n+ 1 day,1 Stop,"21,324"
104,Vistara,29/10/2021,Lucknow,Mumbai,8h 00m,15:25,23:25,2 Stop(s),"21,785"
105,Air India,29/10/2021,Lucknow,Mumbai,13h 30m,08:55,22:25,2 Stop(s),"23,792"

In [174]:
# clear the text in source
driver.find_element_by_id("origin_0").clear()

In [175]:
search=driver.find_element_by_id('origin_0')
search.send_keys("New Delhi")

In [176]:
# clear the text in destination
driver.find_element_by_id("destination_0").clear()

In [177]:
search=driver.find_element_by_id('destination_0')
search.send_keys("Kolkata")

In [178]:
# clicking on search button
driver.find_element_by_xpath('/html/body/section[1]/section/div/div/form/div[1]/div/button').click()

In [179]:
# clicking on calendar option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]').click()

In [180]:
# clicking on next option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/span').click()

In [181]:
# clicking on next option again
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/span').click()

In [182]:
# clicking on 30th december option
driver.find_element_by_xpath('/html/body/section[2]/section/section[2]/section[1]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/table/tbody/tr[5]/td[5]/div').click()

In [183]:
airline15=[]
source15=[]
des15=[]
dur15=[]
dep15=[]
arvl15=[]
totstops15=[]
price15=[]

In [184]:
# extracting airline name tags
try:
    for i in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']"):
        airline15.append(i.text)
except NoSuchElementException:
    airline15.append("No detail")
    
# extracting source tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b col-4 no-wrap text-right dtime col-3']/p[1]"):
        source15.append(i.text)
except NoSuchElementException:
    source15.append("No detail")
    
# extracting destination tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pdd-0 text-left atime col-5']/p[2]"):
        des15.append(i.text)
except NoSuchElementException:
    des15.append("No detail")
    
# extracting duration tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']"):
        dur15.append(i.text)
except NoSuchElementException:
    dur15.append("No detail")
    
# extracting departure time tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='i-b pr']"):
        dep15.append(i.text)
except NoSuchElementException:
    dep15.append("No detail")
    
# extracting arrival time tags
try:
    for i in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']"):
        arvl15.append(i.text)
except NoSuchElementException:
    arvl15.append("No detail")
    
# extracting total stops tags
try:
    for i in driver.find_elements_by_xpath("//div[@class=' font-lightgrey fs-10 tipsy i-b fs-10']"):
        totstops15.append(i.text)
except NoSuchElementException:
    totstops15.append("No detail")
    
# extracting price tags
try:
    for i in driver.find_elements_by_xpath("//div[@class='pr i-b mr-2']"):
        price15.append(i.text)
except NoSuchElementException:
    price15.append("No detail")

In [185]:
len(price15)

141

In [186]:
doj15=['30/12/2021']
doj15=doj15*141

In [187]:
flight15=pd.DataFrame({})            # making dataframe
flight15['Airline']= airline15
flight15['Date_of_Journey']=doj15
flight15['Source']= source15
flight15['Destination']= des15
flight15['Duration']= dur15
flight15['Departure Time']= dep15
flight15['Arrival Time']= arvl15
flight15['Total Stops']=totstops15
flight15['Price']= price15
flight15

,Airline,Date_of_Journey,Source,Destination,Duration,Departure Time,Arrival Time,Total Stops,Price
0,Air India,30/12/2021,New Delhi,Kolkata,2h 20m,12:10,14:30,Non Stop,"1 left at2,482"
1,IndiGo,30/12/2021,New Delhi,Kolkata,5h 00m,06:00,11:00,1 Stop,"2 left at3,818"
2,Air Asia,30/12/2021,New Delhi,Kolkata,2h 10m,05:00,07:10,Non Stop,"3,999"
3,Air Asia,30/12/2021,New Delhi,Kolkata,2h 10m,21:00,23:10,Non Stop,"3,999"
4,Air Asia,30/12/2021,New Delhi,Kolkata,2h 25m,16:50,19:15,Non Stop,"3,999"
...,...,...,...,...,...,...,...,...,...
136,Air India,30/12/2021,New Delhi,Kolkata,27h 55m,04:55,08:50\n+ 1 day,2 Stop(s),"11,871"
137,Vistara,30/12/2021,New Delhi,Kolkata,16h 35m,17:10,09:45\n+ 1 day,2 Stop(s),"3 left at12,539"
138,SpiceJet,30/12/2021,New Delhi,Kolkata,24h 05m,13:05,13:10\n+ 1 day,1 Stop,"17,206"
139,SpiceJet,30/12/2021,New Delhi,Kolkata,8h 00m,09:25,17:25,1 Stop,"17,836"
140,Air India,30/12/2021,New Delhi,Kolkata,29h 10m,05:30,10:40\n+ 1 day,2 Stop(s),"31,618"

In [188]:
flight=pd.concat([flight1, flight2, flight3, flight4, flight5, flight6, flight7, flight8,
                 flight9, flight10, flight11, flight12, flight13, flight14, flight15])

In [189]:
compression_opts = dict(method='zip',
                        archive_name='webscraped_data.csv')  
flight.to_csv('webscraped_data.zip', index=False,
          compression=compression_opts)

In [190]:
# to close the driver
driver.close()